name: viscan_food_delivery_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

# ================== PACKAGES ==================

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2

# ================== PACKAGES END ==================
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # ================== LOCAL ASSETS ==================
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
# ================== LOCAL ASSETS END ==================

# ================== LOCAL FONTS ==================

